### ISSUE TITLE
Weird stacking

### ISSUE THREAD

**Issue by zoidTheHuman** [monteslu/bggapp#4]
I am accessing the site with Firefox and have noticed two problems (both on the screenshot below):
1 - It does not handle "(" and ")" very well.
2 - When the game description (name and/or year) have a different size from the rest of the row it seems to cause a weird "stacking".
![bggpicker](https://cloud.githubusercontent.com/assets/14943005/10250747/0d67fa7e-6903-11e5-82be-83bd5f16ff39.jpg)

**Comment by monteslu** [comment]
yeah.  thinking about just showing the images like WhatToPlay does and having you click on a game for full details.
Will that work?

**Comment by zoidTheHuman** [comment]
WTPD shows the title, too and I think it is important. As for the published date, not so much.
Are you planning on having a full details page on BGG Picker itself or just linking to BGG? 
Also, maybe clicking on the image itself to get you there is maybe more user-friendly.

**Comment by monteslu** [comment]
cool, I'll just trim the long titles and make the whole item a link.  Was thinking showing the full details the collection API gives and including a link to BGG from that view. Similar to WhatToPlay

**Comment by zoidTheHuman** [comment]
That would be nice, mainly because it will be useful for setups composed of devices with low bandwidth and/or difficult input interface (like a Raspberry Pi+TV Remote)

**Comment by monteslu** [comment]
@zoidTheHuman 
pushed some updates, give it another shot

**Comment by zoidTheHuman** [comment]
The details page and the image clicking are working fine!
The stacking problem is gone, but it is still not handling the characters "(" and ")" very well.

**Comment by monteslu** [comment]
Cool.  will close this issue, and open another for the weird character encodings.  I think the BGG xmlapi is mangling things unessarily, but it might be on my end.

**Comment by zoidTheHuman** [comment]
seems like the problem of weird stacking has creeped up again. Do you require more data (or pictures) about it?
